// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/p2p/proto/image.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DescribeImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageRef      string                 `protobuf:"bytes,1,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeImageRequest) Reset() {
	*x = DescribeImageRequest{}
	mi := &file_internal_p2p_proto_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeImageRequest) ProtoMessage() {}

func (x *DescribeImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeImageRequest.ProtoReflect.Descriptor instead.
func (*DescribeImageRequest) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_image_proto_rawDescGZIP(), []int{0}
}

func (x *DescribeImageRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

type DescribeImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	ImageRef      string                 `protobuf:"bytes,2,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	TargetDigest  string                 `protobuf:"bytes,3,opt,name=target_digest,json=targetDigest,proto3" json:"target_digest,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeImageResponse) Reset() {
	*x = DescribeImageResponse{}
	mi := &file_internal_p2p_proto_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeImageResponse) ProtoMessage() {}

func (x *DescribeImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeImageResponse.ProtoReflect.Descriptor instead.
func (*DescribeImageResponse) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_image_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeImageResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *DescribeImageResponse) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *DescribeImageResponse) GetTargetDigest() string {
	if x != nil {
		return x.TargetDigest
	}
	return ""
}

func (x *DescribeImageResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DescribeImageResponse) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ImageContentDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaType     string                 `protobuf:"bytes,1,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Annotations   map[string]string      `protobuf:"bytes,5,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageContentDescriptor) Reset() {
	*x = ImageContentDescriptor{}
	mi := &file_internal_p2p_proto_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageContentDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageContentDescriptor) ProtoMessage() {}

func (x *ImageContentDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageContentDescriptor.ProtoReflect.Descriptor instead.
func (*ImageContentDescriptor) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_image_proto_rawDescGZIP(), []int{2}
}

func (x *ImageContentDescriptor) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ImageContentDescriptor) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ImageContentDescriptor) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ImageContentDescriptor) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ImageContentDescriptor) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type GetImageContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageRef      string                 `protobuf:"bytes,1,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageContentRequest) Reset() {
	*x = GetImageContentRequest{}
	mi := &file_internal_p2p_proto_image_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageContentRequest) ProtoMessage() {}

func (x *GetImageContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_image_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageContentRequest.ProtoReflect.Descriptor instead.
func (*GetImageContentRequest) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_image_proto_rawDescGZIP(), []int{3}
}

func (x *GetImageContentRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

type GetImageContentResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Found         bool                      `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	ImageRef      string                    `protobuf:"bytes,2,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	Target        *ImageContentDescriptor   `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Platform      string                    `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Labels        map[string]string         `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Descriptors   []*ImageContentDescriptor `protobuf:"bytes,6,rep,name=descriptors,proto3" json:"descriptors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageContentResponse) Reset() {
	*x = GetImageContentResponse{}
	mi := &file_internal_p2p_proto_image_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageContentResponse) ProtoMessage() {}

func (x *GetImageContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_image_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageContentResponse.ProtoReflect.Descriptor instead.
func (*GetImageContentResponse) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_image_proto_rawDescGZIP(), []int{4}
}

func (x *GetImageContentResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetImageContentResponse) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *GetImageContentResponse) GetTarget() *ImageContentDescriptor {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *GetImageContentResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetImageContentResponse) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *GetImageContentResponse) GetDescriptors() []*ImageContentDescriptor {
	if x != nil {
		return x.Descriptors
	}
	return nil
}

type GetImageBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	ChunkSize     uint64                 `protobuf:"varint,2,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint64                 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageBlobRequest) Reset() {
	*x = GetImageBlobRequest{}
	mi := &file_internal_p2p_proto_image_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageBlobRequest) ProtoMessage() {}

func (x *GetImageBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_image_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageBlobRequest.ProtoReflect.Descriptor instead.
func (*GetImageBlobRequest) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_image_proto_rawDescGZIP(), []int{5}
}

func (x *GetImageBlobRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *GetImageBlobRequest) GetChunkSize() uint64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *GetImageBlobRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetImageBlobRequest) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type GetImageBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageBlobResponse) Reset() {
	*x = GetImageBlobResponse{}
	mi := &file_internal_p2p_proto_image_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageBlobResponse) ProtoMessage() {}

func (x *GetImageBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_image_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageBlobResponse.ProtoReflect.Descriptor instead.
func (*GetImageBlobResponse) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_image_proto_rawDescGZIP(), []int{6}
}

func (x *GetImageBlobResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *GetImageBlobResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetImageBlobResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetImageBlobResponse) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type UploadImageArchiveChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	ImageRef      string                 `protobuf:"bytes,2,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,5,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageArchiveChunkRequest) Reset() {
	*x = UploadImageArchiveChunkRequest{}
	mi := &file_internal_p2p_proto_image_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageArchiveChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageArchiveChunkRequest) ProtoMessage() {}

func (x *UploadImageArchiveChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_image_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageArchiveChunkRequest.ProtoReflect.Descriptor instead.
func (*UploadImageArchiveChunkRequest) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_image_proto_rawDescGZIP(), []int{7}
}

func (x *UploadImageArchiveChunkRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadImageArchiveChunkRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *UploadImageArchiveChunkRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *UploadImageArchiveChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadImageArchiveChunkRequest) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type UploadImageArchiveChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceivedBytes uint64                 `protobuf:"varint,1,opt,name=received_bytes,json=receivedBytes,proto3" json:"received_bytes,omitempty"`
	Loaded        bool                   `protobuf:"varint,2,opt,name=loaded,proto3" json:"loaded,omitempty"`
	ImageRef      string                 `protobuf:"bytes,3,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	TargetDigest  string                 `protobuf:"bytes,4,opt,name=target_digest,json=targetDigest,proto3" json:"target_digest,omitempty"`
	Platform      string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageArchiveChunkResponse) Reset() {
	*x = UploadImageArchiveChunkResponse{}
	mi := &file_internal_p2p_proto_image_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageArchiveChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageArchiveChunkResponse) ProtoMessage() {}

func (x *UploadImageArchiveChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_image_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageArchiveChunkResponse.ProtoReflect.Descriptor instead.
func (*UploadImageArchiveChunkResponse) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_image_proto_rawDescGZIP(), []int{8}
}

func (x *UploadImageArchiveChunkResponse) GetReceivedBytes() uint64 {
	if x != nil {
		return x.ReceivedBytes
	}
	return 0
}

func (x *UploadImageArchiveChunkResponse) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *UploadImageArchiveChunkResponse) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *UploadImageArchiveChunkResponse) GetTargetDigest() string {
	if x != nil {
		return x.TargetDigest
	}
	return ""
}

func (x *UploadImageArchiveChunkResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

var File_internal_p2p_proto_image_proto protoreflect.FileDescriptor

const file_internal_p2p_proto_image_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/p2p/proto/image.proto\x12\x05proto\"3\n" +
	"\x14DescribeImageRequest\x12\x1b\n" +
	"\timage_ref\x18\x01 \x01(\tR\bimageRef\"\x88\x02\n" +
	"\x15DescribeImageResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1b\n" +
	"\timage_ref\x18\x02 \x01(\tR\bimageRef\x12#\n" +
	"\rtarget_digest\x18\x03 \x01(\tR\ftargetDigest\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12@\n" +
	"\x06labels\x18\x05 \x03(\v2(.proto.DescribeImageResponse.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x02\n" +
	"\x16ImageContentDescriptor\x12\x1d\n" +
	"\n" +
	"media_type\x18\x01 \x01(\tR\tmediaType\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12P\n" +
	"\vannotations\x18\x05 \x03(\v2..proto.ImageContentDescriptor.AnnotationsEntryR\vannotations\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x16GetImageContentRequest\x12\x1b\n" +
	"\timage_ref\x18\x01 \x01(\tR\bimageRef\"\xdf\x02\n" +
	"\x17GetImageContentResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1b\n" +
	"\timage_ref\x18\x02 \x01(\tR\bimageRef\x125\n" +
	"\x06target\x18\x03 \x01(\v2\x1d.proto.ImageContentDescriptorR\x06target\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12B\n" +
	"\x06labels\x18\x05 \x03(\v2*.proto.GetImageContentResponse.LabelsEntryR\x06labels\x12?\n" +
	"\vdescriptors\x18\x06 \x03(\v2\x1d.proto.ImageContentDescriptorR\vdescriptors\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"|\n" +
	"\x13GetImageBlobRequest\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x02 \x01(\x04R\tchunkSize\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x04R\x06length\"l\n" +
	"\x14GetImageBlobResponse\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof\"\x98\x01\n" +
	"\x1eUploadImageArchiveChunkRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x1b\n" +
	"\timage_ref\x18\x02 \x01(\tR\bimageRef\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x05 \x01(\bR\x03eof\"\xbe\x01\n" +
	"\x1fUploadImageArchiveChunkResponse\x12%\n" +
	"\x0ereceived_bytes\x18\x01 \x01(\x04R\rreceivedBytes\x12\x16\n" +
	"\x06loaded\x18\x02 \x01(\bR\x06loaded\x12\x1b\n" +
	"\timage_ref\x18\x03 \x01(\tR\bimageRef\x12#\n" +
	"\rtarget_digest\x18\x04 \x01(\tR\ftargetDigest\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform2\xf7\x01\n" +
	"\x06Images\x12L\n" +
	"\rDescribeImage\x12\x1b.proto.DescribeImageRequest\x1a\x1c.proto.DescribeImageResponse\"\x00\x12R\n" +
	"\x0fGetImageContent\x12\x1d.proto.GetImageContentRequest\x1a\x1e.proto.GetImageContentResponse\"\x00\x12K\n" +
	"\fGetImageBlob\x12\x1a.proto.GetImageBlobRequest\x1a\x1b.proto.GetImageBlobResponse\"\x000\x01B\tZ\a./protob\x06proto3"

var (
	file_internal_p2p_proto_image_proto_rawDescOnce sync.Once
	file_internal_p2p_proto_image_proto_rawDescData []byte
)

func file_internal_p2p_proto_image_proto_rawDescGZIP() []byte {
	file_internal_p2p_proto_image_proto_rawDescOnce.Do(func() {
		file_internal_p2p_proto_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_p2p_proto_image_proto_rawDesc), len(file_internal_p2p_proto_image_proto_rawDesc)))
	})
	return file_internal_p2p_proto_image_proto_rawDescData
}

var file_internal_p2p_proto_image_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_p2p_proto_image_proto_goTypes = []any{
	(*DescribeImageRequest)(nil),            // 0: proto.DescribeImageRequest
	(*DescribeImageResponse)(nil),           // 1: proto.DescribeImageResponse
	(*ImageContentDescriptor)(nil),          // 2: proto.ImageContentDescriptor
	(*GetImageContentRequest)(nil),          // 3: proto.GetImageContentRequest
	(*GetImageContentResponse)(nil),         // 4: proto.GetImageContentResponse
	(*GetImageBlobRequest)(nil),             // 5: proto.GetImageBlobRequest
	(*GetImageBlobResponse)(nil),            // 6: proto.GetImageBlobResponse
	(*UploadImageArchiveChunkRequest)(nil),  // 7: proto.UploadImageArchiveChunkRequest
	(*UploadImageArchiveChunkResponse)(nil), // 8: proto.UploadImageArchiveChunkResponse
	nil,                                     // 9: proto.DescribeImageResponse.LabelsEntry
	nil,                                     // 10: proto.ImageContentDescriptor.AnnotationsEntry
	nil,                                     // 11: proto.GetImageContentResponse.LabelsEntry
}
var file_internal_p2p_proto_image_proto_depIdxs = []int32{
	9,  // 0: proto.DescribeImageResponse.labels:type_name -> proto.DescribeImageResponse.LabelsEntry
	10, // 1: proto.ImageContentDescriptor.annotations:type_name -> proto.ImageContentDescriptor.AnnotationsEntry
	2,  // 2: proto.GetImageContentResponse.target:type_name -> proto.ImageContentDescriptor
	11, // 3: proto.GetImageContentResponse.labels:type_name -> proto.GetImageContentResponse.LabelsEntry
	2,  // 4: proto.GetImageContentResponse.descriptors:type_name -> proto.ImageContentDescriptor
	0,  // 5: proto.Images.DescribeImage:input_type -> proto.DescribeImageRequest
	3,  // 6: proto.Images.GetImageContent:input_type -> proto.GetImageContentRequest
	5,  // 7: proto.Images.GetImageBlob:input_type -> proto.GetImageBlobRequest
	1,  // 8: proto.Images.DescribeImage:output_type -> proto.DescribeImageResponse
	4,  // 9: proto.Images.GetImageContent:output_type -> proto.GetImageContentResponse
	6,  // 10: proto.Images.GetImageBlob:output_type -> proto.GetImageBlobResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_internal_p2p_proto_image_proto_init() }
func file_internal_p2p_proto_image_proto_init() {
	if File_internal_p2p_proto_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_p2p_proto_image_proto_rawDesc), len(file_internal_p2p_proto_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_p2p_proto_image_proto_goTypes,
		DependencyIndexes: file_internal_p2p_proto_image_proto_depIdxs,
		MessageInfos:      file_internal_p2p_proto_image_proto_msgTypes,
	}.Build()
	File_internal_p2p_proto_image_proto = out.File
	file_internal_p2p_proto_image_proto_goTypes = nil
	file_internal_p2p_proto_image_proto_depIdxs = nil
}
