syntax = "proto3";

package proto;


option go_package = "./proto";

service PeerDB {
  rpc ExecSQL(ExecSQLRequest) returns (ExecSQLResponse) {}
  rpc GetAllCommits(GetAllCommitsRequest) returns (GetAllCommitsResponse) {}
  rpc GetHead(GetHeadRequest) returns (GetHeadResponse) {}
}

message ExecSQLRequest {
  string statement = 1;
  int32 max_rows = 2;
}

message ExecSQLResponse {
  repeated string columns = 1;
  repeated SQLRow rows = 2;
  bool truncated = 3;
  string message = 4;
}

message SQLCell {
  string value = 1;
  bool is_null = 2;
}

message SQLRow {
  repeated SQLCell cells = 1;
}

message Commit {
  string hash = 1;
  string committer = 2;
  string message = 3;
  int64 date_unix = 4;
  repeated string parent_hashes = 5;
  repeated string refs = 6;
}

message GetAllCommitsRequest {
}

message GetAllCommitsResponse {
  repeated Commit commits = 1;
}

message GetHeadRequest {
}

message GetHeadResponse {
  string commit = 1;
}
