// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: internal/p2p/proto/peerDB.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PeerDB_ExecSQL_FullMethodName       = "/proto.PeerDB/ExecSQL"
	PeerDB_GetAllCommits_FullMethodName = "/proto.PeerDB/GetAllCommits"
	PeerDB_GetCommitDiff_FullMethodName = "/proto.PeerDB/GetCommitDiff"
	PeerDB_GetHead_FullMethodName       = "/proto.PeerDB/GetHead"
)

// PeerDBClient is the client API for PeerDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeerDBClient interface {
	ExecSQL(ctx context.Context, in *ExecSQLRequest, opts ...grpc.CallOption) (*ExecSQLResponse, error)
	GetAllCommits(ctx context.Context, in *GetAllCommitsRequest, opts ...grpc.CallOption) (*GetAllCommitsResponse, error)
	GetCommitDiff(ctx context.Context, in *GetCommitDiffRequest, opts ...grpc.CallOption) (*GetCommitDiffResponse, error)
	GetHead(ctx context.Context, in *GetHeadRequest, opts ...grpc.CallOption) (*GetHeadResponse, error)
}

type peerDBClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerDBClient(cc grpc.ClientConnInterface) PeerDBClient {
	return &peerDBClient{cc}
}

func (c *peerDBClient) ExecSQL(ctx context.Context, in *ExecSQLRequest, opts ...grpc.CallOption) (*ExecSQLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecSQLResponse)
	err := c.cc.Invoke(ctx, PeerDB_ExecSQL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDBClient) GetAllCommits(ctx context.Context, in *GetAllCommitsRequest, opts ...grpc.CallOption) (*GetAllCommitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllCommitsResponse)
	err := c.cc.Invoke(ctx, PeerDB_GetAllCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDBClient) GetCommitDiff(ctx context.Context, in *GetCommitDiffRequest, opts ...grpc.CallOption) (*GetCommitDiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommitDiffResponse)
	err := c.cc.Invoke(ctx, PeerDB_GetCommitDiff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerDBClient) GetHead(ctx context.Context, in *GetHeadRequest, opts ...grpc.CallOption) (*GetHeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHeadResponse)
	err := c.cc.Invoke(ctx, PeerDB_GetHead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerDBServer is the server API for PeerDB service.
// All implementations should embed UnimplementedPeerDBServer
// for forward compatibility.
type PeerDBServer interface {
	ExecSQL(context.Context, *ExecSQLRequest) (*ExecSQLResponse, error)
	GetAllCommits(context.Context, *GetAllCommitsRequest) (*GetAllCommitsResponse, error)
	GetCommitDiff(context.Context, *GetCommitDiffRequest) (*GetCommitDiffResponse, error)
	GetHead(context.Context, *GetHeadRequest) (*GetHeadResponse, error)
}

// UnimplementedPeerDBServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeerDBServer struct{}

func (UnimplementedPeerDBServer) ExecSQL(context.Context, *ExecSQLRequest) (*ExecSQLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecSQL not implemented")
}
func (UnimplementedPeerDBServer) GetAllCommits(context.Context, *GetAllCommitsRequest) (*GetAllCommitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllCommits not implemented")
}
func (UnimplementedPeerDBServer) GetCommitDiff(context.Context, *GetCommitDiffRequest) (*GetCommitDiffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommitDiff not implemented")
}
func (UnimplementedPeerDBServer) GetHead(context.Context, *GetHeadRequest) (*GetHeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHead not implemented")
}
func (UnimplementedPeerDBServer) testEmbeddedByValue() {}

// UnsafePeerDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerDBServer will
// result in compilation errors.
type UnsafePeerDBServer interface {
	mustEmbedUnimplementedPeerDBServer()
}

func RegisterPeerDBServer(s grpc.ServiceRegistrar, srv PeerDBServer) {
	// If the following call panics, it indicates UnimplementedPeerDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeerDB_ServiceDesc, srv)
}

func _PeerDB_ExecSQL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecSQLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDBServer).ExecSQL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDB_ExecSQL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDBServer).ExecSQL(ctx, req.(*ExecSQLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDB_GetAllCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllCommitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDBServer).GetAllCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDB_GetAllCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDBServer).GetAllCommits(ctx, req.(*GetAllCommitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDB_GetCommitDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommitDiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDBServer).GetCommitDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDB_GetCommitDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDBServer).GetCommitDiff(ctx, req.(*GetCommitDiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerDB_GetHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDBServer).GetHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDB_GetHead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDBServer).GetHead(ctx, req.(*GetHeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeerDB_ServiceDesc is the grpc.ServiceDesc for PeerDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PeerDB",
	HandlerType: (*PeerDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecSQL",
			Handler:    _PeerDB_ExecSQL_Handler,
		},
		{
			MethodName: "GetAllCommits",
			Handler:    _PeerDB_GetAllCommits_Handler,
		},
		{
			MethodName: "GetCommitDiff",
			Handler:    _PeerDB_GetCommitDiff_Handler,
		},
		{
			MethodName: "GetHead",
			Handler:    _PeerDB_GetHead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/p2p/proto/peerDB.proto",
}
