// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/p2p/proto/instance.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OriginDevice          string                 `protobuf:"bytes,1,opt,name=origin_device,json=originDevice,proto3" json:"origin_device,omitempty"`
	OriginDevicePublicKey string                 `protobuf:"bytes,2,opt,name=origin_device_public_key,json=originDevicePublicKey,proto3" json:"origin_device_public_key,omitempty"`
	OriginSwarmionAddrs   []string               `protobuf:"bytes,3,rep,name=origin_swarmion_addrs,json=originSwarmionAddrs,proto3" json:"origin_swarmion_addrs,omitempty"`
	InstanceName          string                 `protobuf:"bytes,4,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_internal_p2p_proto_instance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_instance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_instance_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetOriginDevice() string {
	if x != nil {
		return x.OriginDevice
	}
	return ""
}

func (x *InitRequest) GetOriginDevicePublicKey() string {
	if x != nil {
		return x.OriginDevicePublicKey
	}
	return ""
}

func (x *InitRequest) GetOriginSwarmionAddrs() []string {
	if x != nil {
		return x.OriginSwarmionAddrs
	}
	return nil
}

func (x *InitRequest) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Architecture  string                 `protobuf:"bytes,1,opt,name=architecture,proto3" json:"architecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_internal_p2p_proto_instance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_instance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_instance_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

type GetPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersRequest) Reset() {
	*x = GetPeersRequest{}
	mi := &file_internal_p2p_proto_instance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersRequest) ProtoMessage() {}

func (x *GetPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_instance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersRequest.ProtoReflect.Descriptor instead.
func (*GetPeersRequest) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_instance_proto_rawDescGZIP(), []int{2}
}

type GetPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         map[string]string      `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersResponse) Reset() {
	*x = GetPeersResponse{}
	mi := &file_internal_p2p_proto_instance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersResponse) ProtoMessage() {}

func (x *GetPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_instance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersResponse.ProtoReflect.Descriptor instead.
func (*GetPeersResponse) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_instance_proto_rawDescGZIP(), []int{3}
}

func (x *GetPeersResponse) GetPeers() map[string]string {
	if x != nil {
		return x.Peers
	}
	return nil
}

type GetLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsRequest) Reset() {
	*x = GetLogsRequest{}
	mi := &file_internal_p2p_proto_instance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsRequest) ProtoMessage() {}

func (x *GetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_instance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_instance_proto_rawDescGZIP(), []int{4}
}

type GetLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          string                 `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsResponse) Reset() {
	*x = GetLogsResponse{}
	mi := &file_internal_p2p_proto_instance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsResponse) ProtoMessage() {}

func (x *GetLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_p2p_proto_instance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return file_internal_p2p_proto_instance_proto_rawDescGZIP(), []int{5}
}

func (x *GetLogsResponse) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

var File_internal_p2p_proto_instance_proto protoreflect.FileDescriptor

const file_internal_p2p_proto_instance_proto_rawDesc = "" +
	"\n" +
	"!internal/p2p/proto/instance.proto\x12\x05proto\"\xc4\x01\n" +
	"\vInitRequest\x12#\n" +
	"\rorigin_device\x18\x01 \x01(\tR\foriginDevice\x127\n" +
	"\x18origin_device_public_key\x18\x02 \x01(\tR\x15originDevicePublicKey\x122\n" +
	"\x15origin_swarmion_addrs\x18\x03 \x03(\tR\x13originSwarmionAddrs\x12#\n" +
	"\rinstance_name\x18\x04 \x01(\tR\finstanceName\"2\n" +
	"\fInitResponse\x12\"\n" +
	"\farchitecture\x18\x01 \x01(\tR\farchitecture\"\x11\n" +
	"\x0fGetPeersRequest\"\x86\x01\n" +
	"\x10GetPeersResponse\x128\n" +
	"\x05peers\x18\x01 \x03(\v2\".proto.GetPeersResponse.PeersEntryR\x05peers\x1a8\n" +
	"\n" +
	"PeersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x10\n" +
	"\x0eGetLogsRequest\"%\n" +
	"\x0fGetLogsResponse\x12\x12\n" +
	"\x04logs\x18\x01 \x01(\tR\x04logs2\xb8\x01\n" +
	"\bInstance\x121\n" +
	"\x04Init\x12\x12.proto.InitRequest\x1a\x13.proto.InitResponse\"\x00\x12=\n" +
	"\bGetPeers\x12\x16.proto.GetPeersRequest\x1a\x17.proto.GetPeersResponse\"\x00\x12:\n" +
	"\aGetLogs\x12\x15.proto.GetLogsRequest\x1a\x16.proto.GetLogsResponse\"\x00B\tZ\a./protob\x06proto3"

var (
	file_internal_p2p_proto_instance_proto_rawDescOnce sync.Once
	file_internal_p2p_proto_instance_proto_rawDescData []byte
)

func file_internal_p2p_proto_instance_proto_rawDescGZIP() []byte {
	file_internal_p2p_proto_instance_proto_rawDescOnce.Do(func() {
		file_internal_p2p_proto_instance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_p2p_proto_instance_proto_rawDesc), len(file_internal_p2p_proto_instance_proto_rawDesc)))
	})
	return file_internal_p2p_proto_instance_proto_rawDescData
}

var file_internal_p2p_proto_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_p2p_proto_instance_proto_goTypes = []any{
	(*InitRequest)(nil),      // 0: proto.InitRequest
	(*InitResponse)(nil),     // 1: proto.InitResponse
	(*GetPeersRequest)(nil),  // 2: proto.GetPeersRequest
	(*GetPeersResponse)(nil), // 3: proto.GetPeersResponse
	(*GetLogsRequest)(nil),   // 4: proto.GetLogsRequest
	(*GetLogsResponse)(nil),  // 5: proto.GetLogsResponse
	nil,                      // 6: proto.GetPeersResponse.PeersEntry
}
var file_internal_p2p_proto_instance_proto_depIdxs = []int32{
	6, // 0: proto.GetPeersResponse.peers:type_name -> proto.GetPeersResponse.PeersEntry
	0, // 1: proto.Instance.Init:input_type -> proto.InitRequest
	2, // 2: proto.Instance.GetPeers:input_type -> proto.GetPeersRequest
	4, // 3: proto.Instance.GetLogs:input_type -> proto.GetLogsRequest
	1, // 4: proto.Instance.Init:output_type -> proto.InitResponse
	3, // 5: proto.Instance.GetPeers:output_type -> proto.GetPeersResponse
	5, // 6: proto.Instance.GetLogs:output_type -> proto.GetLogsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_p2p_proto_instance_proto_init() }
func file_internal_p2p_proto_instance_proto_init() {
	if File_internal_p2p_proto_instance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_p2p_proto_instance_proto_rawDesc), len(file_internal_p2p_proto_instance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_p2p_proto_instance_proto_goTypes,
		DependencyIndexes: file_internal_p2p_proto_instance_proto_depIdxs,
		MessageInfos:      file_internal_p2p_proto_instance_proto_msgTypes,
	}.Build()
	File_internal_p2p_proto_instance_proto = out.File
	file_internal_p2p_proto_instance_proto_goTypes = nil
	file_internal_p2p_proto_instance_proto_depIdxs = nil
}
