// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/hostagent/proto/hostagent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DesiredState  *HostDesiredState      `protobuf:"bytes,1,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_internal_hostagent_proto_hostagent_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyRequest) GetDesiredState() *HostDesiredState {
	if x != nil {
		return x.DesiredState
	}
	return nil
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VMObservedState     `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	Network       *NetworkObservedState  `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_internal_hostagent_proto_hostagent_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyResponse) GetVms() []*VMObservedState {
	if x != nil {
		return x.Vms
	}
	return nil
}

func (x *ApplyResponse) GetNetwork() *NetworkObservedState {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *ApplyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VMRef               `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	Network       bool                   `protobuf:"varint,2,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_hostagent_proto_hostagent_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetVms() []*VMRef {
	if x != nil {
		return x.Vms
	}
	return nil
}

func (x *StatusRequest) GetNetwork() bool {
	if x != nil {
		return x.Network
	}
	return false
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VMObservedState     `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	Network       *NetworkObservedState  `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_hostagent_proto_hostagent_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetVms() []*VMObservedState {
	if x != nil {
		return x.Vms
	}
	return nil
}

func (x *StatusResponse) GetNetwork() *NetworkObservedState {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HostDesiredState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VMDesiredState      `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	Network       *NetworkDesiredState   `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostDesiredState) Reset() {
	*x = HostDesiredState{}
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostDesiredState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostDesiredState) ProtoMessage() {}

func (x *HostDesiredState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostDesiredState.ProtoReflect.Descriptor instead.
func (*HostDesiredState) Descriptor() ([]byte, []int) {
	return file_internal_hostagent_proto_hostagent_proto_rawDescGZIP(), []int{4}
}

func (x *HostDesiredState) GetVms() []*VMDesiredState {
	if x != nil {
		return x.Vms
	}
	return nil
}

func (x *HostDesiredState) GetNetwork() *NetworkDesiredState {
	if x != nil {
		return x.Network
	}
	return nil
}

type VMDesiredState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ManifestPath  string                 `protobuf:"bytes,2,opt,name=manifest_path,json=manifestPath,proto3" json:"manifest_path,omitempty"`
	DesiredState  string                 `protobuf:"bytes,3,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMDesiredState) Reset() {
	*x = VMDesiredState{}
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMDesiredState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMDesiredState) ProtoMessage() {}

func (x *VMDesiredState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMDesiredState.ProtoReflect.Descriptor instead.
func (*VMDesiredState) Descriptor() ([]byte, []int) {
	return file_internal_hostagent_proto_hostagent_proto_rawDescGZIP(), []int{5}
}

func (x *VMDesiredState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VMDesiredState) GetManifestPath() string {
	if x != nil {
		return x.ManifestPath
	}
	return ""
}

func (x *VMDesiredState) GetDesiredState() string {
	if x != nil {
		return x.DesiredState
	}
	return ""
}

type VMRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ManifestPath  string                 `protobuf:"bytes,2,opt,name=manifest_path,json=manifestPath,proto3" json:"manifest_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMRef) Reset() {
	*x = VMRef{}
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMRef) ProtoMessage() {}

func (x *VMRef) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMRef.ProtoReflect.Descriptor instead.
func (*VMRef) Descriptor() ([]byte, []int) {
	return file_internal_hostagent_proto_hostagent_proto_rawDescGZIP(), []int{6}
}

func (x *VMRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VMRef) GetManifestPath() string {
	if x != nil {
		return x.ManifestPath
	}
	return ""
}

type VMObservedState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ManifestPath  string                 `protobuf:"bytes,2,opt,name=manifest_path,json=manifestPath,proto3" json:"manifest_path,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Pid           int32                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	PublicIp      string                 `protobuf:"bytes,5,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMObservedState) Reset() {
	*x = VMObservedState{}
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMObservedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMObservedState) ProtoMessage() {}

func (x *VMObservedState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMObservedState.ProtoReflect.Descriptor instead.
func (*VMObservedState) Descriptor() ([]byte, []int) {
	return file_internal_hostagent_proto_hostagent_proto_rawDescGZIP(), []int{7}
}

func (x *VMObservedState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VMObservedState) GetManifestPath() string {
	if x != nil {
		return x.ManifestPath
	}
	return ""
}

func (x *VMObservedState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VMObservedState) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *VMObservedState) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *VMObservedState) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NetworkDesiredState struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DesiredState         string                 `protobuf:"bytes,1,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"`
	Config               *NetworkConfig         `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Instances            []*InstancePeer        `protobuf:"bytes,3,rep,name=instances,proto3" json:"instances,omitempty"`
	Devices              []*DevicePeer          `protobuf:"bytes,4,rep,name=devices,proto3" json:"devices,omitempty"`
	NamespacedInterfaces []*NamespacedInterface `protobuf:"bytes,5,rep,name=namespaced_interfaces,json=namespacedInterfaces,proto3" json:"namespaced_interfaces,omitempty"`
	ReconcilePeers       bool                   `protobuf:"varint,6,opt,name=reconcile_peers,json=reconcilePeers,proto3" json:"reconcile_peers,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NetworkDesiredState) Reset() {
	*x = NetworkDesiredState{}
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkDesiredState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkDesiredState) ProtoMessage() {}

func (x *NetworkDesiredState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkDesiredState.ProtoReflect.Descriptor instead.
func (*NetworkDesiredState) Descriptor() ([]byte, []int) {
	return file_internal_hostagent_proto_hostagent_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkDesiredState) GetDesiredState() string {
	if x != nil {
		return x.DesiredState
	}
	return ""
}

func (x *NetworkDesiredState) GetConfig() *NetworkConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *NetworkDesiredState) GetInstances() []*InstancePeer {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *NetworkDesiredState) GetDevices() []*DevicePeer {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *NetworkDesiredState) GetNamespacedInterfaces() []*NamespacedInterface {
	if x != nil {
		return x.NamespacedInterfaces
	}
	return nil
}

func (x *NetworkDesiredState) GetReconcilePeers() bool {
	if x != nil {
		return x.ReconcilePeers
	}
	return false
}

type NetworkConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Ipv6Address         string                 `protobuf:"bytes,1,opt,name=ipv6_address,json=ipv6Address,proto3" json:"ipv6_address,omitempty"`
	WireguardPrivateKey string                 `protobuf:"bytes,2,opt,name=wireguard_private_key,json=wireguardPrivateKey,proto3" json:"wireguard_private_key,omitempty"`
	Domain              string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_internal_hostagent_proto_hostagent_proto_rawDescGZIP(), []int{9}
}

func (x *NetworkConfig) GetIpv6Address() string {
	if x != nil {
		return x.Ipv6Address
	}
	return ""
}

func (x *NetworkConfig) GetWireguardPrivateKey() string {
	if x != nil {
		return x.WireguardPrivateKey
	}
	return ""
}

func (x *NetworkConfig) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type InstancePeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PublicIp      string                 `protobuf:"bytes,4,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstancePeer) Reset() {
	*x = InstancePeer{}
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstancePeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstancePeer) ProtoMessage() {}

func (x *InstancePeer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstancePeer.ProtoReflect.Descriptor instead.
func (*InstancePeer) Descriptor() ([]byte, []int) {
	return file_internal_hostagent_proto_hostagent_proto_rawDescGZIP(), []int{10}
}

func (x *InstancePeer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstancePeer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstancePeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *InstancePeer) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

type DevicePeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevicePeer) Reset() {
	*x = DevicePeer{}
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevicePeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicePeer) ProtoMessage() {}

func (x *DevicePeer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicePeer.ProtoReflect.Descriptor instead.
func (*DevicePeer) Descriptor() ([]byte, []int) {
	return file_internal_hostagent_proto_hostagent_proto_rawDescGZIP(), []int{11}
}

func (x *DevicePeer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DevicePeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type NamespacedInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetnsPath     string                 `protobuf:"bytes,1,opt,name=netns_path,json=netnsPath,proto3" json:"netns_path,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespacedInterface) Reset() {
	*x = NamespacedInterface{}
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespacedInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespacedInterface) ProtoMessage() {}

func (x *NamespacedInterface) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespacedInterface.ProtoReflect.Descriptor instead.
func (*NamespacedInterface) Descriptor() ([]byte, []int) {
	return file_internal_hostagent_proto_hostagent_proto_rawDescGZIP(), []int{12}
}

func (x *NamespacedInterface) GetNetnsPath() string {
	if x != nil {
		return x.NetnsPath
	}
	return ""
}

func (x *NamespacedInterface) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type NetworkObservedState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Up            bool                   `protobuf:"varint,2,opt,name=up,proto3" json:"up,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkObservedState) Reset() {
	*x = NetworkObservedState{}
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkObservedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkObservedState) ProtoMessage() {}

func (x *NetworkObservedState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hostagent_proto_hostagent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkObservedState.ProtoReflect.Descriptor instead.
func (*NetworkObservedState) Descriptor() ([]byte, []int) {
	return file_internal_hostagent_proto_hostagent_proto_rawDescGZIP(), []int{13}
}

func (x *NetworkObservedState) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *NetworkObservedState) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

func (x *NetworkObservedState) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_hostagent_proto_hostagent_proto protoreflect.FileDescriptor

const file_internal_hostagent_proto_hostagent_proto_rawDesc = "" +
	"\n" +
	"(internal/hostagent/proto/hostagent.proto\x12\thostagent\"P\n" +
	"\fApplyRequest\x12@\n" +
	"\rdesired_state\x18\x01 \x01(\v2\x1b.hostagent.HostDesiredStateR\fdesiredState\"\x92\x01\n" +
	"\rApplyResponse\x12,\n" +
	"\x03vms\x18\x01 \x03(\v2\x1a.hostagent.VMObservedStateR\x03vms\x129\n" +
	"\anetwork\x18\x02 \x01(\v2\x1f.hostagent.NetworkObservedStateR\anetwork\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"M\n" +
	"\rStatusRequest\x12\"\n" +
	"\x03vms\x18\x01 \x03(\v2\x10.hostagent.VMRefR\x03vms\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\bR\anetwork\"\x93\x01\n" +
	"\x0eStatusResponse\x12,\n" +
	"\x03vms\x18\x01 \x03(\v2\x1a.hostagent.VMObservedStateR\x03vms\x129\n" +
	"\anetwork\x18\x02 \x01(\v2\x1f.hostagent.NetworkObservedStateR\anetwork\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"y\n" +
	"\x10HostDesiredState\x12+\n" +
	"\x03vms\x18\x01 \x03(\v2\x19.hostagent.VMDesiredStateR\x03vms\x128\n" +
	"\anetwork\x18\x02 \x01(\v2\x1e.hostagent.NetworkDesiredStateR\anetwork\"j\n" +
	"\x0eVMDesiredState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rmanifest_path\x18\x02 \x01(\tR\fmanifestPath\x12#\n" +
	"\rdesired_state\x18\x03 \x01(\tR\fdesiredState\"<\n" +
	"\x05VMRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rmanifest_path\x18\x02 \x01(\tR\fmanifestPath\"\xa7\x01\n" +
	"\x0fVMObservedState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rmanifest_path\x18\x02 \x01(\tR\fmanifestPath\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x05R\x03pid\x12\x1b\n" +
	"\tpublic_ip\x18\x05 \x01(\tR\bpublicIp\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\xd2\x02\n" +
	"\x13NetworkDesiredState\x12#\n" +
	"\rdesired_state\x18\x01 \x01(\tR\fdesiredState\x120\n" +
	"\x06config\x18\x02 \x01(\v2\x18.hostagent.NetworkConfigR\x06config\x125\n" +
	"\tinstances\x18\x03 \x03(\v2\x17.hostagent.InstancePeerR\tinstances\x12/\n" +
	"\adevices\x18\x04 \x03(\v2\x15.hostagent.DevicePeerR\adevices\x12S\n" +
	"\x15namespaced_interfaces\x18\x05 \x03(\v2\x1e.hostagent.NamespacedInterfaceR\x14namespacedInterfaces\x12'\n" +
	"\x0freconcile_peers\x18\x06 \x01(\bR\x0ereconcilePeers\"~\n" +
	"\rNetworkConfig\x12!\n" +
	"\fipv6_address\x18\x01 \x01(\tR\vipv6Address\x122\n" +
	"\x15wireguard_private_key\x18\x02 \x01(\tR\x13wireguardPrivateKey\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\"n\n" +
	"\fInstancePeer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1b\n" +
	"\tpublic_ip\x18\x04 \x01(\tR\bpublicIp\"?\n" +
	"\n" +
	"DevicePeer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"D\n" +
	"\x13NamespacedInterface\x12\x1d\n" +
	"\n" +
	"netns_path\x18\x01 \x01(\tR\tnetnsPath\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"X\n" +
	"\x14NetworkObservedState\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x0e\n" +
	"\x02up\x18\x02 \x01(\bR\x02up\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x8a\x01\n" +
	"\tHostAgent\x12<\n" +
	"\x05Apply\x12\x17.hostagent.ApplyRequest\x1a\x18.hostagent.ApplyResponse\"\x00\x12?\n" +
	"\x06Status\x12\x18.hostagent.StatusRequest\x1a\x19.hostagent.StatusResponse\"\x00B;Z9github.com/protosio/protos/internal/hostagent/proto;protob\x06proto3"

var (
	file_internal_hostagent_proto_hostagent_proto_rawDescOnce sync.Once
	file_internal_hostagent_proto_hostagent_proto_rawDescData []byte
)

func file_internal_hostagent_proto_hostagent_proto_rawDescGZIP() []byte {
	file_internal_hostagent_proto_hostagent_proto_rawDescOnce.Do(func() {
		file_internal_hostagent_proto_hostagent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_hostagent_proto_hostagent_proto_rawDesc), len(file_internal_hostagent_proto_hostagent_proto_rawDesc)))
	})
	return file_internal_hostagent_proto_hostagent_proto_rawDescData
}

var file_internal_hostagent_proto_hostagent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_hostagent_proto_hostagent_proto_goTypes = []any{
	(*ApplyRequest)(nil),         // 0: hostagent.ApplyRequest
	(*ApplyResponse)(nil),        // 1: hostagent.ApplyResponse
	(*StatusRequest)(nil),        // 2: hostagent.StatusRequest
	(*StatusResponse)(nil),       // 3: hostagent.StatusResponse
	(*HostDesiredState)(nil),     // 4: hostagent.HostDesiredState
	(*VMDesiredState)(nil),       // 5: hostagent.VMDesiredState
	(*VMRef)(nil),                // 6: hostagent.VMRef
	(*VMObservedState)(nil),      // 7: hostagent.VMObservedState
	(*NetworkDesiredState)(nil),  // 8: hostagent.NetworkDesiredState
	(*NetworkConfig)(nil),        // 9: hostagent.NetworkConfig
	(*InstancePeer)(nil),         // 10: hostagent.InstancePeer
	(*DevicePeer)(nil),           // 11: hostagent.DevicePeer
	(*NamespacedInterface)(nil),  // 12: hostagent.NamespacedInterface
	(*NetworkObservedState)(nil), // 13: hostagent.NetworkObservedState
}
var file_internal_hostagent_proto_hostagent_proto_depIdxs = []int32{
	4,  // 0: hostagent.ApplyRequest.desired_state:type_name -> hostagent.HostDesiredState
	7,  // 1: hostagent.ApplyResponse.vms:type_name -> hostagent.VMObservedState
	13, // 2: hostagent.ApplyResponse.network:type_name -> hostagent.NetworkObservedState
	6,  // 3: hostagent.StatusRequest.vms:type_name -> hostagent.VMRef
	7,  // 4: hostagent.StatusResponse.vms:type_name -> hostagent.VMObservedState
	13, // 5: hostagent.StatusResponse.network:type_name -> hostagent.NetworkObservedState
	5,  // 6: hostagent.HostDesiredState.vms:type_name -> hostagent.VMDesiredState
	8,  // 7: hostagent.HostDesiredState.network:type_name -> hostagent.NetworkDesiredState
	9,  // 8: hostagent.NetworkDesiredState.config:type_name -> hostagent.NetworkConfig
	10, // 9: hostagent.NetworkDesiredState.instances:type_name -> hostagent.InstancePeer
	11, // 10: hostagent.NetworkDesiredState.devices:type_name -> hostagent.DevicePeer
	12, // 11: hostagent.NetworkDesiredState.namespaced_interfaces:type_name -> hostagent.NamespacedInterface
	0,  // 12: hostagent.HostAgent.Apply:input_type -> hostagent.ApplyRequest
	2,  // 13: hostagent.HostAgent.Status:input_type -> hostagent.StatusRequest
	1,  // 14: hostagent.HostAgent.Apply:output_type -> hostagent.ApplyResponse
	3,  // 15: hostagent.HostAgent.Status:output_type -> hostagent.StatusResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_internal_hostagent_proto_hostagent_proto_init() }
func file_internal_hostagent_proto_hostagent_proto_init() {
	if File_internal_hostagent_proto_hostagent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_hostagent_proto_hostagent_proto_rawDesc), len(file_internal_hostagent_proto_hostagent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_hostagent_proto_hostagent_proto_goTypes,
		DependencyIndexes: file_internal_hostagent_proto_hostagent_proto_depIdxs,
		MessageInfos:      file_internal_hostagent_proto_hostagent_proto_msgTypes,
	}.Build()
	File_internal_hostagent_proto_hostagent_proto = out.File
	file_internal_hostagent_proto_hostagent_proto_goTypes = nil
	file_internal_hostagent_proto_hostagent_proto_depIdxs = nil
}
