package protoscontracts

// Code generated by hof from CUE catalog; DO NOT EDIT.

import (
	swarmion "github.com/nustiueudinastea/swarmion/runtime"
	v00 "github.com/protosio/protos/internal/db/contracts/sql/protos/v0_0"
	v01 "github.com/protosio/protos/internal/db/contracts/sql/protos/v0_1"
)

var Catalog = swarmion.SchemaCatalogDefinition{
	Surfaces: []swarmion.SchemaSurfaceDefinition{
		{
			ID: "protos.db",
			Versions: []swarmion.SchemaVersionDefinition{
				v00.Version,
				v01.Version,
			},
			Transitions: []swarmion.SchemaTransitionDefinition{
				v00.Transition,
				v01.Transition,
				v01.InitialTransition,
			},
		},
	},
}

var InitialSQL = v00.CreateSQL
