// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/meta.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	core "github.com/protosio/protos/internal/core"
	util "github.com/protosio/protos/internal/util"
	reflect "reflect"
)

// MockMeta is a mock of Meta interface
type MockMeta struct {
	ctrl     *gomock.Controller
	recorder *MockMetaMockRecorder
}

// MockMetaMockRecorder is the mock recorder for MockMeta
type MockMetaMockRecorder struct {
	mock *MockMeta
}

// NewMockMeta creates a new mock instance
func NewMockMeta(ctrl *gomock.Controller) *MockMeta {
	mock := &MockMeta{ctrl: ctrl}
	mock.recorder = &MockMetaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMeta) EXPECT() *MockMetaMockRecorder {
	return m.recorder
}

// InitCheck mocks base method
func (m *MockMeta) InitCheck() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InitCheck")
}

// InitCheck indicates an expected call of InitCheck
func (mr *MockMetaMockRecorder) InitCheck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitCheck", reflect.TypeOf((*MockMeta)(nil).InitCheck))
}

// GetPublicIP mocks base method
func (m *MockMeta) GetPublicIP() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicIP")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPublicIP indicates an expected call of GetPublicIP
func (mr *MockMetaMockRecorder) GetPublicIP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicIP", reflect.TypeOf((*MockMeta)(nil).GetPublicIP))
}

// GetDomain mocks base method
func (m *MockMeta) GetDomain() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDomain")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDomain indicates an expected call of GetDomain
func (mr *MockMetaMockRecorder) GetDomain() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDomain", reflect.TypeOf((*MockMeta)(nil).GetDomain))
}

// GetTLSCertificate mocks base method
func (m *MockMeta) GetTLSCertificate() core.Resource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTLSCertificate")
	ret0, _ := ret[0].(core.Resource)
	return ret0
}

// GetTLSCertificate indicates an expected call of GetTLSCertificate
func (mr *MockMetaMockRecorder) GetTLSCertificate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTLSCertificate", reflect.TypeOf((*MockMeta)(nil).GetTLSCertificate))
}

// SetDomain mocks base method
func (m *MockMeta) SetDomain(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDomain", arg0)
}

// SetDomain indicates an expected call of SetDomain
func (mr *MockMetaMockRecorder) SetDomain(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDomain", reflect.TypeOf((*MockMeta)(nil).SetDomain), arg0)
}

// SetAdminUser mocks base method
func (m *MockMeta) SetAdminUser(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAdminUser", arg0)
}

// SetAdminUser indicates an expected call of SetAdminUser
func (mr *MockMetaMockRecorder) SetAdminUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAdminUser", reflect.TypeOf((*MockMeta)(nil).SetAdminUser), arg0)
}

// CreateProtosResources mocks base method
func (m *MockMeta) CreateProtosResources() (map[string]core.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProtosResources")
	ret0, _ := ret[0].(map[string]core.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProtosResources indicates an expected call of CreateProtosResources
func (mr *MockMetaMockRecorder) CreateProtosResources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProtosResources", reflect.TypeOf((*MockMeta)(nil).CreateProtosResources))
}

// GetProtosResources mocks base method
func (m *MockMeta) GetProtosResources() map[string]core.Resource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProtosResources")
	ret0, _ := ret[0].(map[string]core.Resource)
	return ret0
}

// GetProtosResources indicates an expected call of GetProtosResources
func (mr *MockMetaMockRecorder) GetProtosResources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProtosResources", reflect.TypeOf((*MockMeta)(nil).GetProtosResources))
}

// CleanProtosResources mocks base method
func (m *MockMeta) CleanProtosResources() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanProtosResources")
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanProtosResources indicates an expected call of CleanProtosResources
func (mr *MockMetaMockRecorder) CleanProtosResources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanProtosResources", reflect.TypeOf((*MockMeta)(nil).CleanProtosResources))
}

// GetDashboardDomain mocks base method
func (m *MockMeta) GetDashboardDomain() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboardDomain")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDashboardDomain indicates an expected call of GetDashboardDomain
func (mr *MockMetaMockRecorder) GetDashboardDomain() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboardDomain", reflect.TypeOf((*MockMeta)(nil).GetDashboardDomain))
}

// GetService mocks base method
func (m *MockMeta) GetService() util.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService")
	ret0, _ := ret[0].(util.Service)
	return ret0
}

// GetService indicates an expected call of GetService
func (mr *MockMetaMockRecorder) GetService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockMeta)(nil).GetService))
}

// GetAdminUser mocks base method
func (m *MockMeta) GetAdminUser() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUser")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAdminUser indicates an expected call of GetAdminUser
func (mr *MockMetaMockRecorder) GetAdminUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUser", reflect.TypeOf((*MockMeta)(nil).GetAdminUser))
}
